# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d9432bcdedd5473b93be7fd87eea6e1087eba20f7cbeecba07101fc33d441b2b31995cf5be8bd856bcf0eca27fc0a01e30c8045555832b4c7d6d96fdfc5c3b30

test:
  secret_key_base: a05efed91424677f8c05ed3c8d2a3e0485311cc6eebc0abd4ced1b65f34e420ec71483b2a4f357741b7703da51e4421484211f99e992be44d83a8e0b1efb53b5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
